# -*- coding: utf-8 -*-
"""DNI

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fHnAiRWptynQxwEI16045ohh1NQrSng9
"""

def calculaLetra(numeroDni):
  letra = ["T","R","W","A","G","M","Y","F","P","D","X","B","N","J","Z","S","Q","V","H","L","C","K","E"]
  return letra[numeroDni%23]